packaging_format = 2

id = "misskey"
name = "Misskey"
description.en = "Microblogging platform"
description.fr = "Platforme de Microblogging"

version = "12.119.2~ynh1"

maintainers = ["Anmol Sharma"]

[upstream]
license = "AGPL-3.0"
website = "https://misskey-hub.net/"
code = "https://github.com/misskey-dev/misskey"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64" ]
multi_instance = true
ldap = false
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "If enabled, Misskey will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Misskey sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/misskey-dev/misskey/archive/refs/tags/12.119.2.tar.gz"
        sha256 = "0620c8d4ee82f3bfa5749197b719cff606628413875589918df58f71cae9df57"
        autoupdate.strategy = "latest_github_tag"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages ="ffmpeg, postgresql"

    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "postgresql"
